export const CONFIG = {
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY!,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN!,
  ALLOWED_USER_ID: process.env.TELEGRAM_USER_ID!,
  X_BEARER_TOKEN: process.env.X_BEARER_TOKEN || "",
  MODEL: "claude-sonnet-4-6",
  OPUS_MODEL: "claude-opus-4-6",
  MAX_TOOL_ITERATIONS: 25,
  WORKSPACE_DIR: "./workspace",
  MEMORY_FILE: "./data/MEMORY.md",
  DB_PATH: "./data/minion.db",
  SYSTEM_PROMPT_FILE: "./prompts/SYSTEM_PROMPT.md",
  HISTORY_TTL_MINUTES: 60 * 4,
  MAX_HISTORY_MESSAGES: 50,
} as const;
